[build]
  command = "npm run build"
  publish = "."

[build.environment]
  NODE_VERSION = "16"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/js/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/js/modules/*.js"
  [headers.values]
    Content-Type = "application/javascript"

# ENTFERNEN SIE DIESEN REDIRECT:
# [[redirects]]
#   from = "/js/modules/*"
#   to = "/js/:splat"
#   status = 200

# Standard-Redirect für SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
