[build]
  command = "npm run build"
  publish = "."

[build.environment]
  NODE_VERSION = "16"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/js/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/js/modules/*.js"
  [headers.values]
    Content-Type = "application/javascript"

# Standard-Redirect für SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Gesonderte Behandlung für Ping-Anfragen (Network Detector)
[[redirects]]
  from = "/ping"
  to = "/ping-success.txt"
  status = 200
