[build]
  command = "npm run build"
  publish = "."

[build.environment]
  NODE_VERSION = "16"

# Redirect für Module-Pfade
[[redirects]]
  from = "/js/modules/*"
  to = "/js/:splat"
  status = 200

# Standard-Redirect für SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
